#!/bin/bash

# Script: Ops 201 Class 04 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: February 23, 2023
# Purpose: A script that: 
# Creates four directories (dir1, dir2, dir3, dir4)
# Puts the name of the four directories in an array
# References the array variable to create a new .txt file in each directory.

# Create four directories:

mkdir dir1 dir2 dir3 dir4

# Put the names of four directories in an array

puppyArray=("corgi" "labrador" "husky" "poodle")

# Main

echo ${puppyArray[3]}/file4.txt
echo ${puppyArray[2]}/file3.txt
echo ${puppyArray[1]}/file2.txt
echo ${puppyArray[0]}/file1.txt

# End