#!/bin/bash

# Script: Ops 201 Class 04 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: February 23, 2023
# Purpose: A script that: 
# Creates four directories (dir1, dir2, dir3, dir4)
# Puts the name of the four directories in an array
# References the array variable to create a new .txt file in each directory.

# Main

# Create four directories:

# mkdir dir1 dir2 dir3 dir4

# Put the names of the four directories in an array:

# directory_array=("dir1.sh" "dir2.sh" "dir3.sh" "dir4.sh")

# Reference the array variables to create a new .txt file in each directory:


# End