#!/bin/bash

# Script: Ops 201 Class 06 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 2, 2023
# Purpose: Create a script that detects if a file or directory exists, 
#          Then creates it if it does not exist,
#          *Your script must use at least one array, one loop, and one conditional.
# 


# Main

# Create a script that detects if a file or directory exists

if [[ -e "Ivy_Beans" ]]; then
  echo "Ivy Beans exists"
fi

# End
# Resources: https://devhints.io/bash#conditionals,