#!/bin/bash

# Script: Ops 201 Class 06 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 2, 2023
# Purpose: Create a script that detects if a file or directory exists, 
#          Then creates it if it does not exist,
#          *Your script must use at least one array, one loop, and one conditional.

# Main

# Array

beans=('red' 'black' 'pinto')

beans[0]="red"
beans[1]="black"
beans[2]="pinto"

echo ${beans[*]}

# Loop

name="Cool Bean"
echo "$name"
echo "$name"

for $name in "red" "black" "pinto"
do echo $name

# Create a script that detects if a file or directory exists

if [[ -e beans_06.txt ]]; then
  echo beans exist
fi

# Resources: https://devhints.io/bash#conditionals

# End 