#!/bin/bash

# Script: Ops 201 Class 07 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 27, 2023
# Purpose: Create a script that asks a user to type a domain, then displays information about the typed domain.
#          Operations that must be used include: whois, dig, host, nslookup
#          Output the results to a single .txt file and open it with your favorite text editor.
#          For this challenge you must use at least one variable and one function.

# Main



# End