#!/bin/bash

# Script: Ops 201 Class 05 Ops Challenge Solution
# Author: Jasmine Garcia
# Date of latest revision: February 17, 2023
# Purpose: Write a script that displays running processes, asks the user for a PID, then kills the process with that PID. Also, use a loop in your script.


# Main

# asking user to show running processes
echo "User, show me processes that are currently running"

# command to view all processes running 
ps aux

#specify 
echo "Which process would you like to kill?"

kill -9 18493

echo Would you like to eliminate another process?
read no

# End