#!/bin/bash

# Script: Ops 201 Class 13 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 27, 2023
# Purpose: Create a script that asks a user to type a domain, then displays information about the typed domain.
#          Operations that must be used include: whois, dig, host, nslookup
#          Output the results to a single .txt file and open it with your favorite text editor.
#          For this challenge you must use at least one variable and one function.

# variable 
# DomainName=amazon.com
# echo $DomainName
read -p ' What domain name would you like me to look up? ' DomainName 

# Install whois on your Ubuntu VM
# sudo apt-get install whois

# Take a user input string. Presumably the string is a domain name such as Google.com.
# I will use amazon.com

# Main

# Run whois against a user input string.
# Run dig against the user input string.
# Run host against the user input string.
# Run nslookup against the user input string.

display_information () {
    whois $DomainName
    dig $DomainName
    host $DomainName
    nslookup $DomainName
}
display_information > summary.txt

# End