#!/bin/bash

# Script: Ops 201 Class 07 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 6, 2023
# Purpose: Create a script that uses:
# lshw to display system information to the screen about the following components:
# CPU, RAM, Display adapter, Network adapter

# Main

# Name of Computer:
echo "devserver201"

# CPU Information: 
sudo lshw | grep -A6 "cpu"

# RAM Information
sudo lshw | grep -A3 "memory"

# Display adapter information
sudo lshw | grep -A10 "display"

# Network adapter information
sudo lshw | grep -A15 "network"

# End 