#!/bin/bash

# Script: Ops 201 Class 07 Ops Challenge Solution
# Author: Jasmine Garcia 
# Date of latest revision: March 6, 2023
# Purpose: Create a script that uses:
# lshw to display system information to the screen about the following components:
# CPU, RAM, Display adapter, Network adapter

# Main
# End 